apiVersion: apps/v1
kind: Deployment
metadata:
  name: _APP_NAME_
  namespace: _NAMESPACE_
  labels:
    app: _APP_NAME_
spec:
  replicas: 2
  selector:
    matchLabels:
      app: _APP_NAME_

  # Pod template
  template:
    metadata:
      labels:
        app: _APP_NAME_
    spec:
      containers:
        - name: test
          image: registry.gitlab.com/multimatrix/_APP_NAME_:_VERSION_
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:
  name: _APP_NAME_
  namespace: _NAMESPACE_
  labels:
    app: _APP_NAME_
  # annotations:
  #   getambassador.io/config: |
  #     ---
  #     apiVersion: ambassador/v0
  #     kind: Mapping
  #     name: _APP_NAME__mapping
  #     prefix: /
  #     service: _APP_NAME_._NAMESPACE_:8080
spec:
  # type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
      app: _APP_NAME_
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: _APP_NAME_
  namespace: _NAMESPACE_
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: _APP_NAME_
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
